# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GAuthPayload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12GAuthPayload.proto\"\xf0\x02\n\x0cGAuthPayload\x12&\n\x07payload\x18\x01 \x03(\x0b\x32\x15.GAuthPayload.Payload\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x1a\xa3\x01\n\x07Payload\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12$\n\talgorithm\x18\x04 \x01(\x0e\x32\x11.GAuthPayload.Alg\x12\x0e\n\x06\x64igits\x18\x05 \x01(\x05\x12#\n\x04type\x18\x06 \x01(\x0e\x32\x15.GAuthPayload.OtpType\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03\"\x1a\n\x03\x41lg\x12\t\n\x05\x45RROR\x10\x00\x12\x08\n\x04SHA1\x10\x01\"*\n\x07OtpType\x12\x0b\n\x07INVALID\x10\x00\x12\x08\n\x04HOTP\x10\x01\x12\x08\n\x04TOTP\x10\x02\x62\x06proto3')



_GAUTHPAYLOAD = DESCRIPTOR.message_types_by_name['GAuthPayload']
_GAUTHPAYLOAD_PAYLOAD = _GAUTHPAYLOAD.nested_types_by_name['Payload']
_GAUTHPAYLOAD_ALG = _GAUTHPAYLOAD.enum_types_by_name['Alg']
_GAUTHPAYLOAD_OTPTYPE = _GAUTHPAYLOAD.enum_types_by_name['OtpType']
GAuthPayload = _reflection.GeneratedProtocolMessageType('GAuthPayload', (_message.Message,), {

  'Payload' : _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
    'DESCRIPTOR' : _GAUTHPAYLOAD_PAYLOAD,
    '__module__' : 'GAuthPayload_pb2'
    # @@protoc_insertion_point(class_scope:GAuthPayload.Payload)
    })
  ,
  'DESCRIPTOR' : _GAUTHPAYLOAD,
  '__module__' : 'GAuthPayload_pb2'
  # @@protoc_insertion_point(class_scope:GAuthPayload)
  })
_sym_db.RegisterMessage(GAuthPayload)
_sym_db.RegisterMessage(GAuthPayload.Payload)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAUTHPAYLOAD._serialized_start=23
  _GAUTHPAYLOAD._serialized_end=391
  _GAUTHPAYLOAD_PAYLOAD._serialized_start=156
  _GAUTHPAYLOAD_PAYLOAD._serialized_end=319
  _GAUTHPAYLOAD_ALG._serialized_start=321
  _GAUTHPAYLOAD_ALG._serialized_end=347
  _GAUTHPAYLOAD_OTPTYPE._serialized_start=349
  _GAUTHPAYLOAD_OTPTYPE._serialized_end=391
# @@protoc_insertion_point(module_scope)
